version: '3'
services:
  shopper-mariaDB:
    image: mariadb:latest
    container_name: shopper-mariaDB
    volumes:
      - shopper-mariaDB:/var/lib/mysql/
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    networks:
      - shopper_network

volumes:
  shopper-mariaDB:
    external: true

networks:
  shopper_network:
    external: true
