# Generated by Django 3.1.1 on 2020-09-22 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='p_id',
        ),
        migrations.AddField(
            model_name='products',
            name='purchase_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.purchase'),
        ),
    ]
