# Generated by Django 3.1.1 on 2020-09-22 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200922_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='purchase_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.purchase'),
        ),
    ]
